import type { GalleryWork } from "@/lib/gallery-content";

/** Seed data when `data/gallery-works.json` does not exist yet. */
export const defaultGalleryWorks: GalleryWork[] = [
  {
    id: "sm-01",
    location: "santa-monica",
    title: "Pier morning",
    caption: "Santa Monica Pier — first light, boardwalk closed",
    filename: "santa-monica-01.jpg",
    aspect: "landscape",
    year: 2024,
    tags: [],
  },
  {
    id: "sm-02",
    location: "santa-monica",
    title: "Ocean Park walk",
    caption: "Main Street crossing — cyclists and mist",
    filename: "santa-monica-02.jpg",
    aspect: "portrait",
    year: 2024,
    tags: [],
  },
  {
    id: "sm-03",
    location: "santa-monica",
    title: "Palisades shadow",
    caption: "Palisades Park bench line, winter haze",
    filename: "santa-monica-03.jpg",
    aspect: "landscape",
    year: 2025,
    tags: [],
  },
  {
    id: "sm-04",
    location: "santa-monica",
    title: "Third Street pause",
    caption: "Promenade — window reflection, late afternoon",
    filename: "santa-monica-04.jpg",
    aspect: "square",
    year: 2025,
    tags: [],
  },
  {
    id: "sm-05",
    location: "santa-monica",
    title: "Bike path cadence",
    caption: "Marvin Braude Trail — parallel motion",
    filename: "santa-monica-05.jpg",
    aspect: "landscape",
    year: 2025,
    tags: [],
  },
  {
    id: "sm-06",
    location: "santa-monica",
    title: "Shutters down",
    caption: "Montana Avenue — rain on awnings",
    filename: "santa-monica-06.jpg",
    aspect: "portrait",
    year: 2025,
    tags: [],
  },
  {
    id: "vb-01",
    location: "venice-beach",
    title: "Boardwalk drift",
    caption: "Ocean Front Walk — skaters in sodium light",
    filename: "venice-beach-01.jpg",
    aspect: "landscape",
    year: 2024,
    tags: [],
  },
  {
    id: "vb-02",
    location: "venice-beach",
    title: "Muscle Beach fence",
    caption: "Workout yard — chalk dust and chain link",
    filename: "venice-beach-02.jpg",
    aspect: "portrait",
    year: 2024,
    tags: [],
  },
  {
    id: "vb-03",
    location: "venice-beach",
    title: "Canal reflection",
    caption: "Venice Canals — still water, duplicated façades",
    filename: "venice-beach-03.jpg",
    aspect: "landscape",
    year: 2025,
    tags: [],
  },
  {
    id: "vb-04",
    location: "venice-beach",
    title: "Abbot Kinney stride",
    caption: "Abbot Kinney Blvd — storefront geometry",
    filename: "venice-beach-04.jpg",
    aspect: "square",
    year: 2025,
    tags: [],
  },
  {
    id: "vb-05",
    location: "venice-beach",
    title: "Sunset pier line",
    caption: "Venice Fishing Pier — fishermen at blue hour",
    filename: "venice-beach-05.jpg",
    aspect: "landscape",
    year: 2025,
    tags: [],
  },
  {
    id: "vb-06",
    location: "venice-beach",
    title: "Windward corner",
    caption: "Windward Circle — palm silhouette, traffic pause",
    filename: "venice-beach-06.jpg",
    aspect: "portrait",
    year: 2025,
    tags: [],
  },
];
